// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdg78IpofAFcWaMAtepJKVRLlNctnnWBI',
    appId: '1:692314871844:web:09ac6ca4c98374d5bce0b1',
    messagingSenderId: '692314871844',
    projectId: 'cab-system-7dab6',
    authDomain: 'cab-system-7dab6.firebaseapp.com',
    storageBucket: 'cab-system-7dab6.firebasestorage.app',
    measurementId: 'G-6QHWFSB8PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE5LCY4Vf6alK6k9g5dnnAlAnTTpt7Cok',
    appId: '1:692314871844:android:7a3fc9d62cbad299bce0b1',
    messagingSenderId: '692314871844',
    projectId: 'cab-system-7dab6',
    storageBucket: 'cab-system-7dab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2P3fveIAmjmmALigVqHj9m5L-0BecxTY',
    appId: '1:692314871844:ios:c742362911404638bce0b1',
    messagingSenderId: '692314871844',
    projectId: 'cab-system-7dab6',
    storageBucket: 'cab-system-7dab6.firebasestorage.app',
    iosBundleId: 'com.example.superWheels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2P3fveIAmjmmALigVqHj9m5L-0BecxTY',
    appId: '1:692314871844:ios:c742362911404638bce0b1',
    messagingSenderId: '692314871844',
    projectId: 'cab-system-7dab6',
    storageBucket: 'cab-system-7dab6.firebasestorage.app',
    iosBundleId: 'com.example.superWheels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdg78IpofAFcWaMAtepJKVRLlNctnnWBI',
    appId: '1:692314871844:web:a9695ac82778c5f1bce0b1',
    messagingSenderId: '692314871844',
    projectId: 'cab-system-7dab6',
    authDomain: 'cab-system-7dab6.firebaseapp.com',
    storageBucket: 'cab-system-7dab6.firebasestorage.app',
    measurementId: 'G-TR0C44BVZC',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
